---
# tasks file for letsencrypt
- name: Use correct Python virtual environment package name
  set_fact: virtual_env="{{ 'virtualenv' if (((ansible_distribution == 'Debian') and (ansible_distribution_version >= '8')) or ((ansible_distribution == 'Ubuntu') and (ansible_distribution_version|int >= '14.04'))) else 'python-virtualenv' }}"

- name: Install common packages
  apt:
    name={{ item }}
    update_cache=yes
    cache_valid_time=86400
    install-recommends=no
    state=present
  with_items:
   - ca-certificates
   - dialog
   - gcc
   - git-core
   - libaugeas0
   - libffi-dev
   - python
   - python-dev
   - "{{ virtual_env }}"
#   - libssl-dev

- name: clone git repository
  git:
    repo=https://github.com/letsencrypt/letsencrypt
    dest={{ letsencrypt_git }}
    depth=1
    accept_hostkey=yes

- name: Install python requirements
  pip:
    requirements={{ letsencrypt_git }}/requirements.txt
    virtualenv={{ letsencrypt_venv }}
    virtualenv_site_packages=no
    chdir={{ letsencrypt_venv }}

- name: Install python packages
  pip:
    name={{ letsencrypt_git }}/{{ item }}
    virtualenv={{ letsencrypt_venv }}
    virtualenv_site_packages=yes
    state=present
  with_items:
    - acme
    - .
    - letsencrypt-apache/
    - letsencrypt-nginx/

- name: Installation quirk workaround
  command:
    cp {{ letsencrypt_git }}/{{ item.src }} {{ letsencrypt_venv }}/local/lib/python2.7/site-packages/{{ item.dest }}
    creates="{{ letsencrypt_venv }}/local/lib/python2.7/site-packages/{{ item.dest }}"
  with_items:
    - src: letsencrypt-apache/letsencrypt_apache/options-ssl-apache.conf
      dest: letsencrypt_apache/options-ssl-apache.conf
    - src: letsencrypt-nginx/letsencrypt_nginx/options-ssl-nginx.conf
      dest: letsencrypt_nginx/options-ssl-nginx.conf
    
